# Service name
service: ${env:NAME}
useDotenv: true
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:REGION}
  timeout: ${env:TIMEOUT_SECONDS}
  stage: staging

# package:
#   individually: true

custom:
  webpack:
    includeModules: false

functions:
  protectedAPI1:
    handler: functions/protectedAPI1/index.handler
    events:
      - http:
          path: protected-resource-1
          method: get
          authorizer: authLambda

  protectedAPI2:
    handler: functions/protectedAPI2/index.handler
    events:
      - http:
          path: protected-resource-2
          method: get
          authorizer: authLambda

  authLambda:
    handler: functions/auth/index.handler
    type: token
