name: Lambda Authorizer Tutorial CD
on:
  push:
    branches:
      - staging

jobs:
  deploy-code:
    name: Deploy Lambdas to AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set branch output to variable
        id: branch-name
        run: echo stage=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Set env.ENVIRONMENT_NAME
        run: |
          if [[ ${{steps.branch-name.outputs.stage}} == 'staging' ]]; then
              echo "ENVIRONMENT_NAME=staging" >> "$GITHUB_ENV"
          fi

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Get AWS permissions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.roleToAssume }}
          aws-region: ${{ secrets.region }}

      - name: Deploy
        run: yarn deploy
