name: Lambda Authorizer Tutorial CI
on:
  pull_request:
    branches:
      - staging

jobs:
  lint-and-test:
    name: Lint and test the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint
